### PR TITLE
Introduce workflow to use this repo as Helm repo

### PR DESCRIPTION
**Pull request by lucaam**
* **Please check if the PR fulfills these requirements**
- [x] The branch naming convention follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

<placeholder>

* **What is the current behavior?** (You can also link to an open issue here)

<placeholder>

* **What is the new behavior (if this is a feature change)?**

<placeholder>

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

<placeholder>

* **Other information**:

<placeholder>

Issue: #8

### CODE REVIEW

**Comment by fonzdm** [comment]
@imgios I will let you handle this, I am busy right now with other stuff.

**Review by imgios — CHANGES_REQUESTED** [review]
Hi @lucaam,
Thank you for the effort and the following PR.

I'm sorry, but I have to request some changes based on the [answer provided by @fonzdm in the issue](https://github.com/fonzdm/servarr/issues/8#issuecomment-2097908994).

Please, since @fonzdm prefers to (1) keep the current repo structure and (2) use ArtifactHub, can you:

- Revert the repository structure to the one currently in use in the `dev` branch
- Focus on a separate pipeline that will take the Helm Chart tar and push it towards the ArtifactHub

Will be waiting for you changes. Have fun! 🚀

**Comment by imgios** [comment]
And please, can you fill the PR template fields? I see you are still missing the following ones:

- What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
- What is the current behavior? (You can also link to an open issue here)
- What is the new behavior (if this is a feature change)?
- Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

Thank you! ☺

**Comment by fonzdm** [comment]
@lucaam we will take this from now on, we discovered that artifacthub.io is just an index for helm charts and we need to deploy directly using github pages and, if possible, ghrc oci repo.
😄

**Pull request closed without merging**
